const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '..', 'platform.html'), 'utf8');
const siteHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');

function contains(snippet) {
  assert(
    html.includes(snippet),
    `Expected platform.html to contain: ${snippet}`
  );
}

contains('ABQ ADU — Platform (Version 7.2)');
contains('data-tab="estimates"');
contains('id="tab-estimates"');
contains('Estimates &amp; Invoices');
contains('Version 7.2 · estimate-to-invoice');
contains('Version 7.2 builder app');
contains('InvoiceShelf back-office engine');
contains('ABQ ADU remains the builder cockpit');
contains('Sync to InvoiceShelf');
contains('const ESTIMATE_CATALOG =');
contains('aduBuild285');
contains('ADU consumer price - complete construction estimate at $285 per square foot');
contains('onclick="addEstimateSqftBuildLine()"');
contains('function addEstimateSqftBuildLine()');
contains('$285/sf consumer pricing');
contains('Total / sq ft');
contains('Consumer price basis');
contains('function defaultEstimateState()');
contains('let estimateState = store.get(\'estimateV7\'');
contains('function renderEstimateTool()');
contains('id="estimate-workflow"');
contains('data-estimate-step="client"');
contains('const ESTIMATE_BUNDLES =');
contains('function renderEstimateWorkflow(t)');
contains('function addEstimateCatalogItem(key)');
contains('function addEstimateBundle(key)');
contains('function confirmClearEstimateLines()');
contains("onclick=\"addEstimateBundle('starter')\"");
contains('function convertEstimateToInvoice()');
contains('Invoice Payment Tracker');
contains('id="estimate-payment-status"');
contains('id="estimate-paid-amount"');
contains('id="estimate-paid-date"');
contains('id="estimate-late-fee"');
contains('id="estimate-paid-out"');
contains('id="estimate-balance-out"');
contains('id="estimate-late-fee-out"');
contains('function recordEstimatePayment(kind)');
contains('Record partial payment');
contains('Mark paid in full');
contains('function markEstimateViewed()');
contains('function buildEstimateInvoiceDocument()');
contains('Payment status');
contains('Balance due');
contains('function printEstimateDocument()');
contains('function textEstimateSummary()');
contains("phone:'505-977-7659'");
contains("address:'131 Madison NE, Albuquerque, NM 87108'");
contains("logo:'images/abqadu-logo.png'");
contains('class="print-doc-logo"');
contains('Hosted client links');
contains('Stripe Connect payments');
contains('QuickBooks Online sync');
contains('Financing widget');
contains('Change orders');
contains('openBuilderPrintDocument(`${docLabel} ${docNumber || \'\'}`.trim()');
assert(!html.includes('Version 6'), 'Expected platform.html visible/version copy to be upgraded to Version 7.2');
assert(!siteHtml.includes('Version 6'), 'Expected index.html visible/version copy to be upgraded to Version 7.2');

contains('class="bid-app-shell no-print"');
contains('id="app-project-title"');
contains('onclick="newProjectFolder()"');
contains('onclick="saveBidDraft()"');
contains('onclick="acceptBid()"');
contains('customer call to site visit within 24 hours');
contains('From customer call to <span>site visit</span> in 24 hours');
contains('Above typical 750 sf homeowner ADU planning max');
contains('Typical homeowner max ADU');
contains('Extra electric meter / panel allowance — low range');
contains('Ian internal: sewer confirmation study');
contains('Homeowner Utility Summary');
contains('Sewer confirmation study: verify the ADU toilet and drainage will work properly');
contains('const cityPermitDraw=Math.round(t.total*.5*100)/100;');
contains('Pre-construction contract + city permitting deposit');
contains('City permitting complete / construction start draw — 50% of total bid');
contains('Progress draw — remaining construction balance');
contains('onclick="printBidsAndInvoicing()"');
contains('data-flow-step="site"');
contains('function renderBidAppShell(t)');
contains('renderBidAppShell(t)');
contains('id="quick-cogs-form"');
contains('id="quick-cogs-desc"');
contains('id="quick-cogs-cost"');
contains('function addQuickCogsLine()');
contains('function addCogsBundle(key)');
contains('const COGS_BUNDLES =');
contains('onclick="addCogsBundle(\'dryIn\')"');
contains('onclick="loadAmherstAlturaBenchmark()"');
contains('function loadAmherstAlturaBenchmark()');
contains('435 Amherst Dr NE, Albuquerque NM 87106');
contains('$185,000 / 600 sf = $308 per sf');
contains('current estimate range $150-$170/sf');
contains("if(markup)markup.value='74.1'");
contains('Finish Subcontractor Bid Pulls');
contains('onclick="addCogsBundle(\'finishTradePulls\')"');
contains('Countertops subcontractor bid pull');
contains('Flooring subcontractor bid pull');
contains('Tile subcontractor bid pull');
contains('Cabinets subcontractor bid pull');
contains('Pull finish subcontractor quotes for countertops, flooring, tile, and cabinets on every job.');
contains('Blueprint-to-materials workflow');
contains('Choose model');
contains('Generate takeoff');
contains('Pull supplier / Lowe\'s package');
contains('Pull finish subcontractor quotes');
contains('Import / compare final COGS');
contains('const BLUEPRINT_MATERIAL_GROUPS =');
contains('Slab package');
contains('Lumber / framing package');
contains('Roof package');
contains('Exterior finish package');
contains('Windows / doors package');
contains('Insulation package');
contains('Sheetrock + mud package');
contains('Electrical package');
contains('Plumbing package');
contains('HVAC package');
contains('Flooring quote pull');
contains('Tile quote pull');
contains('Cabinets quote pull');
contains('Countertops quote pull');
contains('id="bp-review-flags"');
contains('Extra electric meter / panel: carry $3,500-$6,500 review allowance.');
contains('Sewer confirmation study: verify route, tie-in, slope, and pump/equipment risk before final bid.');
contains('Openings over 3 ft: engineering review before ordering windows, doors, or headers.');
contains('Typical homeowner ADU max: 750 sf; larger models route to custom review.');
contains('Lowe\'s Pro Cart · 12th Street Lowe\'s');
contains('Preferred Pro Desk');
contains("12th Street Lowe's Pro");
contains('Deliver to job site in drops');
contains('Ramie becomes employee');
contains('Supplier Quote Comparator');
contains('Patton-style workshop takeoff, 8 Alpine Series windows at $2,100');
contains('const SUPPLIER_QUOTES=');
contains('RAKS Hardware');
contains('Jonathan Baca');
contains('Outside Sales');
contains('108 Carson Drive, Los Lunas, NM 87031');
contains('5056594186');
contains('5058663259');
contains('5058651100');
contains('jonathanb@raksmail.com');
contains("Lowe's Pro Desk");
contains('Amber');
contains('Muras PUR/SIP Panels');
contains('Pre-cut PUR panel / SIP system package');
contains('PUR/SIP panel shell package');
contains('Up-front panel package replaces exterior sheathing, framing, insulation, and exterior framing labor/time');
contains('Assembly Cost Comparison');
contains('PUR/SIP panels can cost more up front, but that single package may replace conventional exterior wall framing, exterior sheathing, insulation, and related framing labor/time.');
contains('function renderAssemblyCompare(lines)');
contains('Project Revenue Optimizer');
contains('Compare procurement routes on the current project to maximize builder revenue');
contains('Muras PUR/SIP panels, Lowe\'s package, RAKS openings/hardware, and Rio Grande building package');
contains('Do not stack every supplier line into the bid.');
contains('function revenueRoutes(lines)');
contains('function renderRevenueOptimizer(lines)');
contains('Best margin path');
contains('Projected gross profit');
contains('Revenue score');
contains('sipLaborReduction');
contains('Estimated labor reduction credit');
contains('Labor impact');
contains('labor credit');
contains('Conventional stick build');
contains('Muras PUR/SIP panel path');
contains('Includes exterior sheathing, framing, insulation, and exterior wall assembly');
contains('Can reduce field labor and schedule time even if the package line looks higher');
contains('Rio Grande Building Company');
contains('delivery, price, quality, and availability');
contains('function renderSupplierCompare()');
contains('function textSupplierQuote(id)');
contains('function sendSupplierQuoteToBid(id)');
contains('Build cart priority lines: lumber/2x4s, sheetrock, mud, house wrap, roofing nails, and the roughly $1,000 job-site fastener package.');
contains('2x4 plates and blocking');
contains('Headers, beams, misc framing lumber');
contains('Sheetrock / drywall 4x8 — 1/2 in');
contains('Mud / joint compound — 4.5 gal');
contains('Nails/fasteners/consumables target roughly $1,000 per job site');
contains('id="bid-print-document"');
contains('function buildBidPrintDocument()');
contains('function renderBidPrintDocument()');
contains('function printPanel(panelId, bodyClass=\'\')');
contains('onclick="printInvoicePacket()"');
contains('function printInvoicePacket()');
contains('onclick="printPreconstructionContract()"');
contains('function buildPreconstructionContractDocument()');
contains('function printPreconstructionContract()');
contains('Preconstruction Letter Agreement');
contains('Proposed Contract');
contains('Interim Work');
contains('NMSA 1978, Section 48-2-2');
contains('seven (7) days');
contains('Prototype template for builder workflow');
contains('Preconstruction contract template');
contains('Contractor:</b> _________________________');
contains('Dear ________________________________________________');
assert(!html.includes('Fifth Element Construction'), 'Expected preconstruction contract template to avoid hard-coded contractor names');
contains('function printBidsAndInvoicing()');
contains('function openBuilderPrintDocument(title, subtitle, bodyHtml, fallbackPanelId=\'\', fallbackClass=\'\')');
contains('function buildBuilderPrintShell(title, subtitle, bodyHtml)');
contains('function buildBlueprintBidoutDocument()');
contains('function printBlueprintBidout()');
contains('onclick="printBlueprintBidout()"');
contains('onclick="printLowesQuote()"');
contains('function printLowesQuote()');
contains('openBuilderPrintDocument(`${bid.title || \'ABQ ADU\'} bid packet`');
contains('openBuilderPrintDocument(`${cart.modelName || bid.model || \'ABQ ADU\'} Lowe\'s quote request`');
contains('function exportBidJson()');
contains('function exportBidCsv()');
contains('onclick="exportBidCsv()"');
contains('body.print-bid-summary #tab-bids > :not(#bid-print-document)');
contains('id="export-fallback"');
contains('function showExportFallback(name,content)');
contains('function copyExportFallback()');
contains('id="bid-confidence-grade"');
contains('id="bid-readiness-flags"');
contains('const CONFIDENCE_GRADES =');
contains('function bidReadinessSignals(t)');
contains('function renderBidConfidence(t)');
contains('function toggleReadinessFlag(flag,checked)');
contains('Bid confidence');
contains('ready to send');
contains('needs utility review');
contains('needs engineering');
contains('missing site data');
contains('id="bid-quiz-card"');
contains('id="bid-quiz-answer"');
contains('id="bid-quiz-action"');
contains('function goBidQuizStep(delta)');
contains('function runBidQuizAction()');
contains('function bidQuizCompletion(step,t)');
contains('actionLabel:\'Add COGS line\'');
contains('Bid calculator quiz');
contains('class="invoice-blueprint"');
contains('id="invoice-blueprint-label"');
contains('GB-2 / GB98 Builder Knowledge Base');
contains('GB-2 exam knowledge');
contains('Current license context: GB98');
contains('rough opening (RO)');
contains('king studs');
contains('jack studs');
contains('cripple studs');
contains('header');
contains('sill plate');
contains('sill foam');
contains('zip sill tape when threshold wood is removed');
contains('fireblock');
contains('transom window');
contains('clerestory window');
contains('Some components are interchangeable or substitutable');
contains('Stick Framing Openings');
contains('PUR / SIP Panel Approach');
contains('PUR panels and SIP panel systems are a different build method');
contains('Muras can help provide these panels, and materials/labor COGS may be dramatically reduced versus stick framing.');
contains('Build method matters: stick framing needs RO, header, king studs, jack studs, cripple studs, sill plate, sill foam, zip sill tape, and fireblock review; PUR/SIP panel systems route to Muras/pre-cut panel shop drawings, cut list, connection details, delivery, installation checks, and reduced COGS review.');
contains('confirm build method: stick framing needs RO/header/jack/king/cripple/sill/fireblock review; PUR/SIP panel systems use Muras/pre-cut shop drawings and panel cut lists');
contains('New Mexico 2026 code-cycle watch');
contains('Official New Mexico Register Issue 12 adopted 2024 Plumbing and Mechanical code rules');
contains('2026-08-01');
contains('Code-cycle check before permit handoff');
contains('authority having jurisdiction');
contains('Needs code review.');
contains('function renderCodeCycleWatch()');
contains('NM_CODE_CYCLE');
contains('New Mexico 2026 code-cycle transition');
contains('confirm the active code editions with New Mexico CID and the City of Albuquerque');
contains('Authority having jurisdiction');
contains('Albuquerque');
contains('Santa Fe');
contains('Santa Fe Green Building Code review');
contains('City of Albuquerque Planning / Building Safety requirements');
contains('santafenm.gov/land-use/currently-adopted-codes');
contains('cabq.gov/planning/building-safety-division/building-safety-division');
contains('City regulator phone book');
contains('CITY_REGULATORS');
contains('function renderRegulatorPhonebook()');
contains('function textRegulatorToIan(id)');
contains('City of Albuquerque Building Safety Division');
contains('City of Albuquerque Planning Department');
contains('ABQ 311 Community Contact Center');
contains('City of Santa Fe Building Permit Counter');
contains('City of Santa Fe Green Building Review');
contains('City of Santa Fe Building Inspections');
contains('New Mexico CID Albuquerque Office');
contains('New Mexico CID Santa Fe Office');
contains('permitcounter@santafenm.gov');
contains('roortiz@santafenm.gov');
contains('5059243320');
contains('5059243860');
contains('5059556656');
contains('Text Ian');
contains('Building code assessment tracker');
contains('DEFAULT_CODE_ASSESSMENTS');
contains('codeAssessmentsV7');
contains('function renderCodeAssessments()');
contains('function addCodeAssessment()');
contains('function textCodeAssessmentsToIan()');
contains('State baseline code cycle');
contains('ADU zoning / IDO / permit submittal');
contains('Local code + Green Building review');
contains('Utilities: sewer and electrical');
contains('Openings / structural engineering');
contains('Inspection critical path');
contains('Confirm currently adopted building, residential, electrical, energy, plumbing, mechanical, and fuel gas editions before final bid.');
contains('Restore starter checklist');
contains('Text Ian code status');
contains('Weather delay assessor');
contains('weather-mcp template');
contains('WEATHER_MCP_TOOL_PLAN');
contains('WEATHER_RULES');
contains('WEATHER_SOURCE_CARDS');
contains('weatherDelayEventsV7');
contains('weatherLocationsV7');
contains('function renderWeatherDelayTool');
contains('function weatherEventImpact');
contains('function textWeatherRecoveryPlan');
contains('function saveWeatherLocation');
contains('function addWeatherSample');
contains('function textWeatherEventCrew');
contains('Rain / monsoon');
contains('Wind');
contains('Wildfire smoke / air quality');
contains('Wildfire proximity');
contains('Lightning');
contains('Extreme heat');
contains('Freeze / frost');
contains('get_forecast');
contains('get_air_quality');
contains('get_wildfire_info');
contains('get_lightning_strikes');
contains('critical path');
contains('Text recovery plan');
contains('Save weather location');
contains('Demo monsoon hit');
contains('Demo wind hold');
contains('Demo smoke / AQI');
contains('MCP ready');
contains('Service status');
contains('Text crew');
contains('Builder operating principle');
contains('maximize dollars per day');
contains('minimizing labor cost per day');
contains('Mobile-first triage');

function siteContains(snippet) {
  assert(
    siteHtml.includes(snippet),
    `Expected index.html to contain: ${snippet}`
  );
}

siteContains('ADU Match Wizard<br><span style="color:#2adcf2;">Pick the Right Model First</span>');
siteContains('onclick="printAduMatchReport()"');
siteContains('onclick="printDesignSummary()"');
siteContains('function openHomeownerPrintReport(title, bodyHtml)');
siteContains('function printAduMatchReport()');
siteContains('function printDesignSummary()');
siteContains('Mobile print tip: use Print / Save PDF below.');
siteContains('document.write(doc);');
siteContains('body.adu-match-report-print > *:not(#design)');
siteContains('body.design-summary-print > *:not(.design-result-modal)');
siteContains('Which ADU feels right for your backyard?');
siteContains('What should it look like from the outside?');
siteContains('Who is this ADU for, and how should it feel inside?');
siteContains('Where should we send your ADU concept?');
siteContains('ABQ ADU targets a site visit within 24 hours of the customer call');
siteContains('750 sq ft is treated as the typical maximum planning size');
siteContains('Typical Homeowner Max — 3 variants');
siteContains('Belongs in a larger custom review conversation.');
siteContains('Sewer confirmation study');
siteContains('We confirm the ADU toilet and drainage will work properly');
siteContains('Extra meter low range');
siteContains('Netherwood House');
contains('Netherwood House');
assert(!siteHtml.toLowerCase().includes('macerator'), 'Expected homeowner-facing page to avoid macerator language');
assert(!siteHtml.toLowerCase().includes('masticator'), 'Expected homeowner-facing page to avoid masticator language');
assert(!siteHtml.includes('Hyder Hut'), 'Expected index.html visible copy to use Netherwood House instead of Hyder Hut');
assert(!html.includes('Hyder Hut'), 'Expected platform.html visible copy to use Netherwood House instead of Hyder Hut');
