const assert = require('assert');
const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, '..', 'platform.html'), 'utf8');
const siteHtml = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');

function contains(snippet) {
  assert(
    html.includes(snippet),
    `Expected platform.html to contain: ${snippet}`
  );
}

contains('ABQ ADU — Platform (Version 7)');
contains('data-tab="estimates"');
contains('id="tab-estimates"');
contains('Estimates &amp; Invoices');
contains('Version 7 · estimate-to-invoice');
contains('Version 7 builder app');
contains('const ESTIMATE_CATALOG =');
contains('function defaultEstimateState()');
contains('let estimateState = store.get(\'estimateV7\'');
contains('function renderEstimateTool()');
contains('id="estimate-workflow"');
contains('data-estimate-step="client"');
contains('const ESTIMATE_BUNDLES =');
contains('function renderEstimateWorkflow(t)');
contains('function addEstimateCatalogItem(key)');
contains('function addEstimateBundle(key)');
contains('function confirmClearEstimateLines()');
contains("onclick=\"addEstimateBundle('starter')\"");
contains('function convertEstimateToInvoice()');
contains('Invoice Payment Tracker');
contains('id="estimate-payment-status"');
contains('id="estimate-paid-amount"');
contains('id="estimate-paid-date"');
contains('id="estimate-late-fee"');
contains('id="estimate-paid-out"');
contains('id="estimate-balance-out"');
contains('id="estimate-late-fee-out"');
contains('function recordEstimatePayment(kind)');
contains('Record partial payment');
contains('Mark paid in full');
contains('function markEstimateViewed()');
contains('function buildEstimateInvoiceDocument()');
contains('Payment status');
contains('Balance due');
contains('function printEstimateDocument()');
contains('function textEstimateSummary()');
contains("phone:'505-977-7659'");
contains("address:'131 Madison NE, Albuquerque, NM 87108'");
contains("logo:'images/abqadu-logo.png'");
contains('class="print-doc-logo"');
contains('Hosted client links');
contains('Stripe Connect payments');
contains('QuickBooks Online sync');
contains('Financing widget');
contains('Change orders');
contains('openBuilderPrintDocument(`${docLabel} ${docNumber || \'\'}`.trim()');
assert(!html.includes('Version 6'), 'Expected platform.html visible/version copy to be upgraded to Version 7');
assert(!siteHtml.includes('Version 6'), 'Expected index.html visible/version copy to be upgraded to Version 7');

contains('class="bid-app-shell no-print"');
contains('id="app-project-title"');
contains('onclick="newProjectFolder()"');
contains('onclick="saveBidDraft()"');
contains('onclick="acceptBid()"');
contains('customer call to site visit within 24 hours');
contains('From customer call to <span>site visit</span> in 24 hours');
contains('Above typical 750 sf homeowner ADU planning max');
contains('Typical homeowner max ADU');
contains('Extra electric meter / panel allowance — low range');
contains('Ian internal: sewer confirmation study');
contains('Homeowner Utility Summary');
contains('Sewer confirmation study: verify the ADU toilet and drainage will work properly');
contains('const cityPermitDraw=Math.round(t.total*.5*100)/100;');
contains('Pre-construction contract + city permitting deposit');
contains('City permitting complete / construction start draw — 50% of total bid');
contains('Progress draw — remaining construction balance');
contains('onclick="printBidsAndInvoicing()"');
contains('data-flow-step="site"');
contains('function renderBidAppShell(t)');
contains('renderBidAppShell(t)');
contains('id="quick-cogs-form"');
contains('id="quick-cogs-desc"');
contains('id="quick-cogs-cost"');
contains('function addQuickCogsLine()');
contains('function addCogsBundle(key)');
contains('const COGS_BUNDLES =');
contains('onclick="addCogsBundle(\'dryIn\')"');
contains('Finish Subcontractor Bid Pulls');
contains('onclick="addCogsBundle(\'finishTradePulls\')"');
contains('Countertops subcontractor bid pull');
contains('Flooring subcontractor bid pull');
contains('Tile subcontractor bid pull');
contains('Cabinets subcontractor bid pull');
contains('Pull finish subcontractor quotes for countertops, flooring, tile, and cabinets on every job.');
contains('Blueprint-to-materials workflow');
contains('Choose model');
contains('Generate takeoff');
contains('Pull supplier / Lowe\'s package');
contains('Pull finish subcontractor quotes');
contains('Import / compare final COGS');
contains('const BLUEPRINT_MATERIAL_GROUPS =');
contains('Slab package');
contains('Lumber / framing package');
contains('Roof package');
contains('Exterior finish package');
contains('Windows / doors package');
contains('Insulation package');
contains('Sheetrock + mud package');
contains('Electrical package');
contains('Plumbing package');
contains('HVAC package');
contains('Flooring quote pull');
contains('Tile quote pull');
contains('Cabinets quote pull');
contains('Countertops quote pull');
contains('id="bp-review-flags"');
contains('Extra electric meter / panel: carry $3,500-$6,500 review allowance.');
contains('Sewer confirmation study: verify route, tie-in, slope, and pump/equipment risk before final bid.');
contains('Openings over 3 ft: engineering review before ordering windows, doors, or headers.');
contains('Typical homeowner ADU max: 750 sf; larger models route to custom review.');
contains('Lowe\'s Pro Cart · 12th Street Lowe\'s');
contains('Preferred Pro Desk');
contains("12th Street Lowe's Pro");
contains('Deliver to job site in drops');
contains('Ramie becomes employee');
contains('Supplier Quote Comparator');
contains('Patton-style workshop takeoff, 8 Alpine Series windows at $2,100');
contains('const SUPPLIER_QUOTES=');
contains('RAKX Hardware');
contains('Jonathan');
contains("Lowe's Pro Desk");
contains('Amber');
contains('Rio Grande Building Company');
contains('delivery, price, quality, and availability');
contains('function renderSupplierCompare()');
contains('function textSupplierQuote(id)');
contains('function sendSupplierQuoteToBid(id)');
contains('Build cart priority lines: lumber/2x4s, sheetrock, mud, house wrap, roofing nails, and the roughly $1,000 job-site fastener package.');
contains('2x4 plates and blocking');
contains('Headers, beams, misc framing lumber');
contains('Sheetrock / drywall 4x8 — 1/2 in');
contains('Mud / joint compound — 4.5 gal');
contains('Nails/fasteners/consumables target roughly $1,000 per job site');
contains('id="bid-print-document"');
contains('function buildBidPrintDocument()');
contains('function renderBidPrintDocument()');
contains('function printPanel(panelId, bodyClass=\'\')');
contains('onclick="printInvoicePacket()"');
contains('function printInvoicePacket()');
contains('function printBidsAndInvoicing()');
contains('function openBuilderPrintDocument(title, subtitle, bodyHtml, fallbackPanelId=\'\', fallbackClass=\'\')');
contains('function buildBuilderPrintShell(title, subtitle, bodyHtml)');
contains('function buildBlueprintBidoutDocument()');
contains('function printBlueprintBidout()');
contains('onclick="printBlueprintBidout()"');
contains('onclick="printLowesQuote()"');
contains('function printLowesQuote()');
contains('openBuilderPrintDocument(`${bid.title || \'ABQ ADU\'} bid packet`');
contains('openBuilderPrintDocument(`${cart.modelName || bid.model || \'ABQ ADU\'} Lowe\'s quote request`');
contains('function exportBidJson()');
contains('function exportBidCsv()');
contains('onclick="exportBidCsv()"');
contains('body.print-bid-summary #tab-bids > :not(#bid-print-document)');
contains('id="export-fallback"');
contains('function showExportFallback(name,content)');
contains('function copyExportFallback()');
contains('id="bid-confidence-grade"');
contains('id="bid-readiness-flags"');
contains('const CONFIDENCE_GRADES =');
contains('function bidReadinessSignals(t)');
contains('function renderBidConfidence(t)');
contains('function toggleReadinessFlag(flag,checked)');
contains('Bid confidence');
contains('ready to send');
contains('needs utility review');
contains('needs engineering');
contains('missing site data');
contains('id="bid-quiz-card"');
contains('id="bid-quiz-answer"');
contains('id="bid-quiz-action"');
contains('function goBidQuizStep(delta)');
contains('function runBidQuizAction()');
contains('function bidQuizCompletion(step,t)');
contains('actionLabel:\'Add COGS line\'');
contains('Bid calculator quiz');
contains('class="invoice-blueprint"');
contains('id="invoice-blueprint-label"');

function siteContains(snippet) {
  assert(
    siteHtml.includes(snippet),
    `Expected index.html to contain: ${snippet}`
  );
}

siteContains('ADU Match Wizard<br><span style="color:#2adcf2;">Pick the Right Model First</span>');
siteContains('onclick="printAduMatchReport()"');
siteContains('onclick="printDesignSummary()"');
siteContains('function openHomeownerPrintReport(title, bodyHtml)');
siteContains('function printAduMatchReport()');
siteContains('function printDesignSummary()');
siteContains('Mobile print tip: use Print / Save PDF below.');
siteContains('document.write(doc);');
siteContains('body.adu-match-report-print > *:not(#design)');
siteContains('body.design-summary-print > *:not(.design-result-modal)');
siteContains('Which ADU feels right for your backyard?');
siteContains('What should it look like from the outside?');
siteContains('Who is this ADU for, and how should it feel inside?');
siteContains('Where should we send your ADU concept?');
siteContains('ABQ ADU targets a site visit within 24 hours of the customer call');
siteContains('750 sq ft is treated as the typical maximum planning size');
siteContains('Typical Homeowner Max — 3 variants');
siteContains('Belongs in a larger custom review conversation.');
siteContains('Sewer confirmation study');
siteContains('We confirm the ADU toilet and drainage will work properly');
siteContains('Extra meter low range');
siteContains('Netherwood House');
contains('Netherwood House');
assert(!siteHtml.toLowerCase().includes('macerator'), 'Expected homeowner-facing page to avoid macerator language');
assert(!siteHtml.toLowerCase().includes('masticator'), 'Expected homeowner-facing page to avoid masticator language');
assert(!siteHtml.includes('Hyder Hut'), 'Expected index.html visible copy to use Netherwood House instead of Hyder Hut');
assert(!html.includes('Hyder Hut'), 'Expected platform.html visible copy to use Netherwood House instead of Hyder Hut');
